AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Style/ClassVars:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
